
# DGP params
seed = 1

n_train = 200
dim_factor = 2
dim_signal = 10
dim_X = 1000
sigma_eta = 1.5
sigma_epsilon = 1

# Model params
num_iter = 500
subsample_fraction = 0.5
weakness = 0.7
pw = 0.5    # probability of multiplying weakness for a feature
pi_thr = 0.5    # selection threshold
